# Dependabot configuration file
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "JhossePaul"
    assignees:
      - "JhossePaul"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    # Group minor and patch updates together
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "JhossePaul"
    assignees:
      - "JhossePaul"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Pre-commit hooks
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "JhossePaul"
    assignees:
      - "JhossePaul"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "pre-commit"
    # Only update pre-commit related packages
    target-branch: "main"
    allow:
      - dependency-name: "pre-commit"
      - dependency-name: "ruff"
      - dependency-name: "mypy"
      - dependency-name: "mkdocs*"
