repos:
  - repo: local
    hooks:

    - id: lint
      name: Linting
      entry: make
      args: [lint]
      language: system

    - id: coverage
      name: Test & Coverage
      entry: make
      args: [coverage]
      language: system
      types: [python]
      pass_filenames: false

    - id: tox
      name: Linting, test and coverage over supported Python versions
      entry: make
      args: [tox]
      language: system
      types: [python]
      pass_filenames: false
