site_name: PySetl
site_description: "A modern, type-driven PySpark ETL Framework"
site_author: "Jhosse Paul Marquez Ruiz"
repo_url: https://github.com/JhossePaul/pysetl
repo_name: JhossePaul/pysetl
copyright: >
  Copyright &copy; 2023–present Paul Marquez.<br>
  PySetl was ported and adapted from <a href="https://github.com/SETL-Framework/setl" target="_blank">SETL</a> &copy; 2020 SETL-Developers.

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.breadcrumbs
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - header.autohide
  palette:
    - scheme: default
      primary: '#377AB1'
      accent: '#FAD745'
      background: '#BCDAFF'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: '#003366'
      accent: '#EE8D24'
      background: '#377AB1'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto, Arial, sans-serif
    code: Fira Mono, monospace
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico

nav:
  - Home:
      - Overview: index.md
      - QuickStart: home/quickstart.md
      - Installation: home/installation.md
      - Examples: home/examples.md
  - User Guide:
      - Motivation: user-guide/index.md
      - Philosophy & Concepts: user-guide/philosophy.md
      - Configuration: user-guide/configuration.md
      - Data Access Layer: user-guide/dal.md
      - Workflow: user-guide/workflow.md
      - PySetl Context: user-guide/pysetl_context.md
  - Advanced Usage:
      - Overview: advanced-usage/index.md
      - Config Builder: advanced-usage/config-builder.md
      - Custom Config: advanced-usage/custom-config.md
      - Custom Connectors: advanced-usage/custom-connectors.md
      - Custom Factories: advanced-usage/custom-factories.md
      - Pipelines: advanced-usage/pipelines.md
      - Dispatcher: advanced-usage/dispatcher.md
      - Modularization: advanced-usage/modularization.md
      - Performance: advanced-usage/performance.md
  - API Reference:
      - Overview: api/overview.md
      - pysetl: api/pysetl.md
      - pysetl.workflow: api/workflow.md
      - pysetl.storage: api/storage.md
      - pysetl.config: api/config.md
      - pysetl.utils: api/utils.md
  - Development:
      - Contributing: development/index.md
      - Roadmap: development/roadmap.md
      - Critical Priority: development/critical-priority.md
      - High Priority: development/high-priority.md
      - Medium Priority: development/medium-priority.md
      - Low Priority: development/low-priority.md
      - Very Low Priority: development/very-low-priority.md
      - Completed Work: development/completed-work.md
      - Code of Conduct: development/code-of-conduct.md

plugins:
  - include-markdown
  - search
  - autorefs
  - git-revision-date-localized
  - git-authors
  - minify
  - awesome-pages
  - literate-nav
  - glightbox
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: google
  - section-index

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.highlight
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
  - assets/css/custom.css
extra_javascript: []

edit_uri: "edit/main/docs/"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JhossePaul/pysetl
